rules:
  - condition:
      level:
        min: 10
        max: 20
      country: US
      daysSinceLastPurchase:
        min: 5
    promotion:
      name: "Gold Promotion"
      discount: 20
  - condition:
      level:
        min: 1
        max: 9
      country: US
    promotion:
      name: "Silver Promotion"
      discount: 10

defaultPromotion:
  name: "No Promotion"
  discount: 0
